version: "3.9"

services:
  api:
    image: aiproject-staging:latest   # ✅ FIXED
    container_name: aryu_api
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8000:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - aryu_network
    deploy:
      resources:
        limits:
          memory: 4g

networks:
  aryu_network:
    driver: bridge