"""
test_multistage_pipeline.py — Comprehensive test suite for the Multi-Stage Resume Extraction Pipeline.

Tests all 20 document variations and architecture requirements:
1. Normal text-based PDFs (Krithigas Digital Marketing resume)
2. Scanned / image-only PDFs (zero text layer, OCR recovery)
3. Image-heavy resumes (embedded graphics, high area ratio)
4. Designed / graphic resumes with visual headers and styled dividers
5. Multi-column resumes (3-column layout)
6. Two-column resumes (Sidebar + Main column, zero interleaving)
7. Resumes with tables
8. Resumes with positioned text boxes
9. Resumes with spanning headers and footers
10. Resumes with contact sections and icons
11. Resumes with unusual fonts and size hierarchies
12. Resumes where text is positioned independently on the page (Canva/Figma stream order)
13. Resumes containing embedded images / screenshots
14. Resumes generated by Canva / Figma / Word / Google Docs
15. Resumes with mixed text + image content
16. Resumes with complex visual layouts
17. Very long resumes (multi-page, 4+ pages)
18. One-page compact resumes
19. Resumes where the PDF has a broken/corrupted text layer (triggering OCR fallback)
20. Scanned resumes where there is no usable text layer (full OCR recovery)
"""

import asyncio
import io
import json
import os
import unittest
from typing import Any, Dict, List
import fitz  # PyMuPDF

from app.modules.resume_builder.pdf_inspector import (
    PDFInspector,
    PDFInspectionReport,
    DocumentType,
)
from app.modules.resume_builder.quality_evaluator import (
    ExtractionQualityEvaluator,
    ExtractionQualityReport,
)
from app.modules.resume_builder.page_renderer import PageRenderer
from app.modules.resume_builder.ocr_engine import OCREngine, OCRExtractionResult
from app.modules.resume_builder.layout_reconstructor import LayoutReconstructor
from app.modules.resume_builder.validator import ResumeSourceValidator, ValidationResult
from app.modules.resume_builder.universal_extractor import (
    UniversalDocumentExtractor,
    ExtractedDocument,
)
from app.modules.resume_builder.ai_parser import ImprovedUniversalResumeParser
from app.modules.resume_builder.deterministic_parser import DeterministicResumeParser
from app.modules.resume_builder.schemas import (
    CanonicalResume,
    PersonalInformation,
    ExperienceItem,
    EducationItem,
    ProjectItem,
    map_to_legacy_parse_dict,
)


def create_krithigas_pdf() -> bytes:
    """Creates a 2-page PDF fixture matching the Digital Marketing Executive test resume."""
    doc = fitz.open()

    # ── Page 1 ──
    p1 = doc.new_page(width=595, height=842)
    # Header
    p1.insert_text((50, 70), "KRITHIGAS", fontsize=18, fontname="Helvetica")
    p1.insert_text((50, 92), "Digital Marketing Executive", fontsize=12, fontname="Helvetica")
    p1.insert_text((50, 115), "CONTACT: Kamarajar colony, Sivaganga, 630561, India | +91 8668065697 | krithi825@gmail.com", fontsize=9, fontname="Helvetica")

    # Summary
    p1.insert_text((50, 145), "PROFESSIONAL SUMMARY", fontsize=12, fontname="Helvetica")
    summary_text = (
        "Digital Marketing Executive with 6 Months of professional experience at Aryu Enterprises Pvt Ltd. "
        "Holds a B.sc in Information Technology and focuses on executing digital growth strategies. "
        "Committed to leveraging technical academic foundations to optimize online marketing performance."
    )
    p1.insert_textbox(fitz.Rect(50, 155, 545, 205), summary_text, fontsize=9, fontname="Helvetica")

    # Experience
    p1.insert_text((50, 225), "EXPERIENCE", fontsize=12, fontname="Helvetica")

    # Role 1
    p1.insert_text((50, 245), "Digital Marketing Executive Internship", fontsize=11, fontname="Helvetica")
    p1.insert_text((420, 245), "Apr 2026 — Present", fontsize=9, fontname="Helvetica")
    p1.insert_text((50, 260), "Aryu Enterprises Pvt Ltd", fontsize=10, fontname="Helvetica")
    p1.insert_text((50, 273), "33/14 Jayammal St, Ayyavoo colony, Aminjikarai Chennai - 600 106", fontsize=8, fontname="Helvetica")
    exp1_bullets = (
        "• Skilled in creating and managing engaging content for Instagram and Facebook, including posts, reels, captions, and content calendars.\n"
        "• Experienced in social media strategy, audience engagement, hashtag research, brand awareness, and performance analysis using social media insights."
    )
    p1.insert_textbox(fitz.Rect(50, 285, 545, 335), exp1_bullets, fontsize=9, fontname="Helvetica")

    # Role 2
    p1.insert_text((50, 355), "Digital Marketing Internship", fontsize=11, fontname="Helvetica")
    p1.insert_text((420, 355), "Dec 2025 — Feb 2026", fontsize=9, fontname="Helvetica")
    p1.insert_text((50, 370), "Inmakes Infotech Pvt Ltd • Cheranallur, Kochi, Ernakulam, Kerala 682 034", fontsize=10, fontname="Helvetica")
    exp2_bullets = (
        "• Gained practical exposure to Digital Marketing through internship training in SEO, Social Media Marketing, content creation, and basic paid advertising.\n"
        "• Worked on keyword research, on-page SEO, social media content planning, Canva creatives, and basic website SEO analysis."
    )
    p1.insert_textbox(fitz.Rect(50, 385, 545, 435), exp2_bullets, fontsize=9, fontname="Helvetica")

    # Projects
    p1.insert_text((50, 455), "PROJECTS", fontsize=12, fontname="Helvetica")
    p1.insert_text((50, 475), "Biokosmetikoftexas - USA", fontsize=11, fontname="Helvetica")
    proj1_desc = (
        "The Biokosmetikoftexas Social Media Marketing project focuses on building a strong and professional online presence for the brand across social media platforms. "
        "Biokosmetikoftexas offers professional skincare products from trusted brands such as Biodroga, Dr. Grandel, and ALEX Cosmetic. "
        "The main objective of this project is to increase brand awareness, educate customers about skincare products, improve audience engagement, and generate more website traffic and sales. "
        "The social media strategy includes creating high-quality product posts, educational carousels, promotional graphics, reels, stories, captions, and targeted hashtags."
    )
    p1.insert_textbox(fitz.Rect(50, 490, 545, 585), proj1_desc, fontsize=9, fontname="Helvetica")

    # ── Page 2 ──
    p2 = doc.new_page(width=595, height=842)

    # Project 2
    p2.insert_text((50, 50), "wpwebsitefix (WordPress content strategy)", fontsize=11, fontname="Helvetica")
    proj2_desc = (
        "The social media strategy includes creating informative posts, carousel designs, reels, stories, captions, and promotional content related to WordPress development, website security, SEO, WooCommerce, website speed, plugin recommendations, maintenance, and troubleshooting. "
        "The content is designed to address common website problems and present wpwebsitefix as a reliable solution for businesses that need professional website support."
    )
    p2.insert_textbox(fitz.Rect(50, 65, 545, 145), proj2_desc, fontsize=9, fontname="Helvetica")

    # Project 3
    p2.insert_text((50, 160), "Yestoboss (Finance content strategy)", fontsize=11, fontname="Helvetica")
    proj3_desc = (
        "The Yestoboss Social Media Marketing project focuses on building a strong digital presence for a finance focused brand through informative, engaging, and easy-to-understand social media content. "
        "The project is designed to help audiences improve their financial knowledge, manage money better, and make more confident financial decisions."
    )
    p2.insert_textbox(fitz.Rect(50, 175, 545, 245), proj3_desc, fontsize=9, fontname="Helvetica")

    # Education
    p2.insert_text((50, 260), "EDUCATION", fontsize=12, fontname="Helvetica")
    p2.insert_text((50, 280), "Mannar hr sec school, Sivagangai", fontsize=10, fontname="Helvetica")
    p2.insert_text((420, 280), "2020 — 2022", fontsize=9, fontname="Helvetica")
    p2.insert_text((50, 300), "B.sc Information Technology, Madurai", fontsize=10, fontname="Helvetica")
    p2.insert_text((420, 300), "2022 – 2025  CGPA: 91%", fontsize=9, fontname="Helvetica")

    # Skills
    p2.insert_text((50, 335), "SKILLS", fontsize=12, fontname="Helvetica")
    skills_text = (
        "• Social Media Marketing\n"
        "• Content Creation\n"
        "• Blog content Writing\n"
        "• Reel & Short-Form Video Content\n"
        "• Talking Head / On-Camera Content\n"
        "• Basic Social Media Analytics & Insights\n"
        "• Basic Video Editing\n"
        "• Capcut\n"
        "• Canva Designing\n"
        "• Keyword Research optimization\n"
        "• Competitor Analysis\n"
        "• Google Analytics"
    )
    p2.insert_textbox(fitz.Rect(50, 350, 545, 550), skills_text, fontsize=9, fontname="Helvetica")

    pdf_bytes = doc.tobytes()
    doc.close()
    return pdf_bytes


def create_scanned_pdf(source_pdf_bytes: bytes) -> bytes:
    """Renders a PDF into raster images and creates an image-only PDF with zero text layer."""
    doc_orig = fitz.open(stream=source_pdf_bytes, filetype="pdf")
    doc_scanned = fitz.open()

    for page in doc_orig:
        pix = page.get_pixmap(dpi=150)
        img_bytes = pix.tobytes("png")
        p_scanned = doc_scanned.new_page(width=page.rect.width, height=page.rect.height)
        p_scanned.insert_image(page.rect, stream=img_bytes)

    scanned_bytes = doc_scanned.tobytes()
    doc_orig.close()
    doc_scanned.close()
    return scanned_bytes


def create_2column_sidebar_pdf() -> bytes:
    """Creates a 2-column sidebar resume (Left: Contact, Skills, Education; Right: Summary, Experience, Projects)."""
    doc = fitz.open()
    p = doc.new_page(width=595, height=842)

    # Spanning Header
    p.insert_text((40, 40), "SARAH CONNOR", fontsize=18, fontname="Helvetica")
    p.insert_text((40, 60), "Lead DevOps Engineer", fontsize=12, fontname="Helvetica")

    # Left Sidebar (x: 40 to 180)
    p.insert_text((40, 95), "CONTACT", fontsize=11, fontname="Helvetica")
    p.insert_text((40, 110), "sarah@cyberdyne.io", fontsize=8, fontname="Helvetica")
    p.insert_text((40, 122), "+1 555 987 6543", fontsize=8, fontname="Helvetica")
    p.insert_text((40, 134), "Los Angeles, CA", fontsize=8, fontname="Helvetica")

    p.insert_text((40, 160), "SKILLS", fontsize=11, fontname="Helvetica")
    p.insert_text((40, 175), "• Kubernetes", fontsize=8, fontname="Helvetica")
    p.insert_text((40, 187), "• Terraform", fontsize=8, fontname="Helvetica")
    p.insert_text((40, 199), "• AWS / GCP", fontsize=8, fontname="Helvetica")
    p.insert_text((40, 211), "• Python & Go", fontsize=8, fontname="Helvetica")
    p.insert_text((40, 223), "• Prometheus", fontsize=8, fontname="Helvetica")

    p.insert_text((40, 250), "EDUCATION", fontsize=11, fontname="Helvetica")
    p.insert_text((40, 265), "B.S. Computer Systems", fontsize=8, fontname="Helvetica")
    p.insert_text((40, 277), "Caltech, 2020", fontsize=8, fontname="Helvetica")

    # Right Main Column (x: 210 to 555)
    p.insert_text((210, 95), "PROFESSIONAL SUMMARY", fontsize=11, fontname="Helvetica")
    p.insert_textbox(
        fitz.Rect(210, 105, 555, 150),
        "Senior infrastructure engineer specializing in automated Kubernetes clusters and zero-trust cloud security.",
        fontsize=9,
        fontname="Helvetica",
    )

    p.insert_text((210, 160), "EXPERIENCE", fontsize=11, fontname="Helvetica")
    p.insert_text((210, 175), "Principal Infrastructure Engineer | Skynet Inc | 2021 - Present", fontsize=9, fontname="Helvetica")
    p.insert_textbox(
        fitz.Rect(210, 188, 555, 240),
        "• Designed multi-region Kubernetes platform handling 250k RPS with 99.999% uptime.\n• Reduced annual cloud expenditure by $1.2M through automated resource bin-packing.",
        fontsize=8,
        fontname="Helvetica",
    )

    p.insert_text((210, 250), "PROJECTS", fontsize=11, fontname="Helvetica")
    p.insert_text((210, 265), "KubeGuard - Security Operator", fontsize=9, fontname="Helvetica")
    p.insert_textbox(
        fitz.Rect(210, 278, 555, 330),
        "Open-source eBPF Kubernetes security operator for runtime threat detection and automated isolation.",
        fontsize=8,
        fontname="Helvetica",
    )

    pdf_bytes = doc.tobytes()
    doc.close()
    return pdf_bytes


def create_canva_interleaved_pdf() -> bytes:
    """Simulates Canva/design tool with independent text boxes inserted in interleaved Z-order."""
    doc = fitz.open()
    p = doc.new_page(width=595, height=842)

    # Interleaved insertions (Left box, Right box, Left box, Right box)
    p.insert_text((40, 50), "SKILLS", fontsize=12)
    p.insert_text((240, 50), "EXPERIENCE", fontsize=12)
    p.insert_text((40, 70), "• Python", fontsize=9)
    p.insert_text((240, 70), "Lead Developer | Tech Corp | 2022 - Present", fontsize=10)
    p.insert_text((40, 85), "• FastAPI", fontsize=9)
    p.insert_text((240, 85), "• Built high-performance microservices.", fontsize=9)
    p.insert_text((40, 100), "• Docker", fontsize=9)
    p.insert_text((240, 100), "• Scaled DB to 10k QPS.", fontsize=9)

    pdf_bytes = doc.tobytes()
    doc.close()
    return pdf_bytes


class TestMultiStageResumeExtractionPipeline(unittest.TestCase):

    # ── Test 1: Normal Text PDF (Krithigas Test Resume) ──
    def test_01_normal_text_pdf_extraction(self):
        pdf_bytes = create_krithigas_pdf()
        doc = UniversalDocumentExtractor.extract_document(pdf_bytes, "krithigas_resume.pdf")

        self.assertEqual(doc.document_type, "text_pdf")
        self.assertTrue(doc.quality_score >= 0.75)
        self.assertFalse(doc.ocr_used)
        self.assertEqual(doc.page_count, 2)
        self.assertIn("KRITHIGAS", doc.raw_text)
        self.assertIn("Aryu Enterprises Pvt Ltd", doc.raw_text)
        self.assertIn("Inmakes Infotech Pvt Ltd", doc.raw_text)
        self.assertIn("Biokosmetikoftexas", doc.raw_text)
        self.assertIn("wpwebsitefix", doc.raw_text)
        self.assertIn("Yestoboss", doc.raw_text)
        self.assertIn("Mannar hr sec school", doc.raw_text)
        self.assertIn("B.sc Information Technology", doc.raw_text)
        self.assertIn("Social Media Marketing", doc.raw_text)

    # ── Test 2: Scanned / Image-Only PDF (Full OCR Recovery) ──
    def test_02_scanned_pdf_ocr_recovery(self):
        krithi_bytes = create_krithigas_pdf()
        scanned_bytes = create_scanned_pdf(krithi_bytes)

        # Verify direct text on scanned PDF is empty
        doc_fitz = fitz.open(stream=scanned_bytes, filetype="pdf")
        self.assertEqual(doc_fitz[0].get_text().strip(), "")
        doc_fitz.close()

        # Extract through UniversalDocumentExtractor
        extracted = UniversalDocumentExtractor.extract_document(scanned_bytes, "scanned_krithigas.pdf")

        self.assertEqual(extracted.document_type, "scanned_pdf")
        self.assertTrue(extracted.ocr_used)
        self.assertTrue(len(extracted.raw_text) > 300)
        self.assertTrue(extracted.quality_score >= 0.70)
        self.assertIn("DIGITAL MARKETING EXECUTIVE", extracted.raw_text.upper())
        self.assertIn("ARYU ENTERPRISES", extracted.raw_text.upper())
        self.assertIn("BIOKOSMETIKOFTEXAS", extracted.raw_text.upper())

    # ── Test 3: Image-Heavy Document Inspection ──
    def test_03_image_heavy_pdf_inspection(self):
        doc = fitz.open()
        p = doc.new_page(width=595, height=842)
        # Add text
        p.insert_text((50, 50), "Jane Doe - Graphic Designer", fontsize=14)
        p.insert_text((50, 70), "Experience: Design Studio | 2020 - Present", fontsize=10)
        # Add large image covering 60% of page
        pix = fitz.Pixmap(fitz.csRGB, fitz.IRect(0, 0, 400, 400), False)
        pix.clear_with(200)
        p.insert_image(fitz.Rect(50, 100, 500, 600), stream=pix.tobytes("png"))

        pdf_bytes = doc.tobytes()
        doc.close()

        report = PDFInspector.inspect(pdf_bytes, "designer_portfolio.pdf")
        self.assertTrue(report.avg_image_area_ratio > 0.35)
        self.assertIn(report.document_type, [DocumentType.IMAGE_HEAVY_PDF, DocumentType.COMPLEX_LAYOUT_PDF])

    # ── Test 4 & 5: Two-Column Sidebar Layout (No Interleaving) ──
    def test_04_twocolumn_sidebar_no_interleaving(self):
        pdf_bytes = create_2column_sidebar_pdf()
        extracted = UniversalDocumentExtractor.extract_document(pdf_bytes, "sarah_sidebar.pdf")

        self.assertIn("SARAH CONNOR", extracted.raw_text)
        self.assertIn("Lead DevOps Engineer", extracted.raw_text)

        # In markdown / blocks, SKILLS and EXPERIENCE should be cleanly separated sections
        self.assertIn("SKILLS", extracted.markdown)
        self.assertIn("EXPERIENCE", extracted.markdown)

        # Verify reading order: Left sidebar items shouldn't be interleaved with right column items
        blocks = extracted.raw_items
        skill_texts = [b["text"] for b in blocks if "Kubernetes" in b["text"] or "Terraform" in b["text"]]
        exp_texts = [b["text"] for b in blocks if "Skynet Inc" in b["text"] or "multi-region" in b["text"]]

        self.assertTrue(len(skill_texts) > 0)
        self.assertTrue(len(exp_texts) > 0)

    # ── Test 6: Canva/Figma Interleaved Positioning Recovery ──
    def test_05_canva_interleaved_position_recovery(self):
        pdf_bytes = create_canva_interleaved_pdf()
        extracted = UniversalDocumentExtractor.extract_document(pdf_bytes, "canva_interleaved.pdf")

        # LayoutReconstructor must reconstruct blocks cleanly
        self.assertTrue(len(extracted.raw_items) >= 4)
        markdown = extracted.markdown
        self.assertIn("SKILLS", markdown)
        self.assertIn("EXPERIENCE", markdown)
        self.assertIn("Python", markdown)
        self.assertIn("FastAPI", markdown)
        self.assertIn("Lead Developer", markdown)

    # ── Test 7: Table-Based Resume ──
    def test_06_table_based_resume(self):
        doc = fitz.open()
        p = doc.new_page(width=595, height=842)
        p.insert_text((50, 40), "David Miller", fontsize=16)
        p.insert_text((50, 60), "david@example.com | +1 555 432 1098", fontsize=9)
        p.insert_text((50, 90), "EDUCATION", fontsize=12)

        # Draw a table with cells
        p.insert_text((50, 110), "Degree | Institution | Year | GPA", fontsize=9)
        p.insert_text((50, 125), "M.S. Software Engineering | Stanford University | 2021 | 3.9", fontsize=9)
        p.insert_text((50, 140), "B.S. Computer Science | UC Berkeley | 2019 | 3.8", fontsize=9)

        p.insert_text((50, 170), "EXPERIENCE", fontsize=12)
        p.insert_text((50, 190), "Senior Software Engineer | Apple | 2021 - Present", fontsize=10)
        p.insert_text((50, 205), "• Built iOS core audio processing pipeline.", fontsize=9)

        pdf_bytes = doc.tobytes()
        doc.close()

        extracted = UniversalDocumentExtractor.extract_document(pdf_bytes, "david_table.pdf")
        self.assertIn("Stanford University", extracted.raw_text)
        self.assertIn("UC Berkeley", extracted.raw_text)
        self.assertIn("Apple", extracted.raw_text)

    # ── Test 8: Extraction Quality Evaluator on High vs Corrupted Text ──
    def test_07_extraction_quality_scoring(self):
        clean_text = (
            "Alex Johnson\n"
            "alex@example.com | +1 555 123 4567 | San Francisco, CA\n"
            "Professional Summary\n"
            "Senior backend engineer with 8 years of experience building distributed systems.\n"
            "Experience\n"
            "Senior Backend Engineer | Stripe | 2021 - Present\n"
            "• Architected distributed payment processing pipeline handling 50k RPS.\n"
            "Education\n"
            "B.S. in Computer Science | UC Berkeley | 2017\n"
            "Skills\n"
            "Python, Go, PostgreSQL, Redis, Kubernetes, Docker\n"
        )
        good_rep = ExtractionQualityEvaluator.evaluate(
            blocks=[{"x": 40, "y": 50, "w": 500, "h": 20, "page": 1, "column": 0, "text": clean_text}],
            raw_text=clean_text,
        )
        self.assertTrue(good_rep.is_reliable)
        self.assertTrue(good_rep.quality_score >= 0.70)
        self.assertIn("experience", good_rep.detected_sections)
        self.assertIn("education", good_rep.detected_sections)
        self.assertIn("skills", good_rep.detected_sections)

        # Test corrupted text
        corrupted_text = "(cid:142)(cid:143)(cid:144) \ufffd\ufffd\ufffd unreadable garbage"
        bad_rep = ExtractionQualityEvaluator.evaluate(
            blocks=[{"x": 40, "y": 50, "w": 500, "h": 20, "page": 1, "column": 0, "text": corrupted_text}],
            raw_text=corrupted_text,
        )
        self.assertFalse(bad_rep.is_reliable)
        self.assertIn("CORRUPTED_FONT_ENCODING", bad_rep.flags)

    # ── Test 9: Source-Grounded Validation (Detecting Hallucinations) ──
    def test_08_source_grounded_validation(self):
        source_text = (
            "KRITHIGAS\n"
            "Digital Marketing Executive Internship at Aryu Enterprises Pvt Ltd (Apr 2026 — Present)\n"
            "Digital Marketing Internship at Inmakes Infotech Pvt Ltd (Dec 2025 — Feb 2026)\n"
            "Projects: Biokosmetikoftexas, wpwebsitefix, Yestoboss\n"
            "Education: B.sc Information Technology, Madurai (2022 - 2025)\n"
            "Skills: SEO, Social Media Marketing, Canva, CapCut, Google Analytics\n"
        )

        # Grounded Resume
        grounded_resume = CanonicalResume(
            personal_information=PersonalInformation(name="Krithigas", title="Digital Marketing Executive"),
            experience=[
                ExperienceItem(position="Digital Marketing Executive Internship", company="Aryu Enterprises Pvt Ltd", fromYear="Apr 2026", toYear="Present"),
                ExperienceItem(position="Digital Marketing Internship", company="Inmakes Infotech Pvt Ltd", fromYear="Dec 2025", toYear="Feb 2026"),
            ],
            projects=[
                ProjectItem(title="Biokosmetikoftexas", description="Social Media Marketing"),
                ProjectItem(title="wpwebsitefix", description="WordPress content strategy"),
                ProjectItem(title="Yestoboss", description="Finance content strategy"),
            ],
            education=[
                EducationItem(degree="B.sc Information Technology", institution="Madurai"),
            ],
            skills=["Social Media Marketing", "Canva", "CapCut", "Google Analytics"],
        )

        val_good = ResumeSourceValidator.validate(grounded_resume, source_text)
        self.assertTrue(val_good.is_valid)
        self.assertEqual(len(val_good.hallucination_warnings), 0)
        self.assertTrue(val_good.score >= 0.85)

        # Hallucinated Resume (AI invented Software Engineer at Google/Microsoft)
        hallucinated_resume = CanonicalResume(
            personal_information=PersonalInformation(name="Krithigas"),
            experience=[
                ExperienceItem(position="Senior Cloud Architect", company="Amazon Web Services", fromYear="2020", toYear="2023"),
                ExperienceItem(position="Staff Engineer", company="Netflix Inc", fromYear="2023", toYear="Present"),
            ],
            projects=[
                ProjectItem(title="Quantum Blockchain Protocol"),
            ],
            education=[
                EducationItem(degree="Ph.D. in Artificial Intelligence", institution="Harvard University"),
            ],
        )

        val_bad = ResumeSourceValidator.validate(hallucinated_resume, source_text)
        self.assertFalse(val_bad.is_valid)
        self.assertTrue(len(val_bad.hallucination_warnings) >= 3)
        self.assertTrue(val_bad.requires_recovery)

    # ── Test 10: Complete Krithigas Resume Retention via Deterministic AST ──
    def test_09_krithigas_resume_entity_retention(self):
        pdf_bytes = create_krithigas_pdf()
        extracted = UniversalDocumentExtractor.extract_document(pdf_bytes, "krithigas.pdf")

        canonical = DeterministicResumeParser.parse_text(extracted.raw_text)
        legacy = map_to_legacy_parse_dict(canonical)

        # Name & Header
        self.assertEqual(legacy["header"]["name"], "Krithigas")
        self.assertIn("krithi825@gmail.com", legacy["header"]["email"])
        self.assertIn("8668065697", legacy["header"]["phone"])

        # Experience (both internships preserved)
        self.assertTrue(len(legacy["experience"]) >= 2)
        exp_titles = [e["position"] for e in legacy["experience"]]
        self.assertTrue(any("Digital Marketing Executive Internship" in t for t in exp_titles))
        self.assertTrue(any("Digital Marketing Internship" in t for t in exp_titles))

        # Projects (all 3 projects retained)
        self.assertTrue(len(legacy["projects"]) >= 3)
        proj_titles = [p["title"] for p in legacy["projects"]]
        self.assertTrue(any("Biokosmetikoftexas" in t for t in proj_titles))
        self.assertTrue(any("wpwebsitefix" in t for t in proj_titles))
        self.assertTrue(any("Yestoboss" in t for t in proj_titles))

        # Education
        self.assertTrue(len(legacy["education"]) >= 1)
        edu_degrees = [e["degree"] for e in legacy["education"]]
        self.assertTrue(any("Information Technology" in d or "B.sc" in d or "High School" in d for d in edu_degrees))

        # Skills
        self.assertTrue(len(legacy["skills"]) >= 8)
        self.assertIn("Social Media Marketing", legacy["skills"])
        self.assertIn("Google Analytics", legacy["skills"])

    # ── Test 11: Very Long Resume (5 Pages) ──
    def test_10_very_long_resume_handling(self):
        doc = fitz.open()
        for i in range(5):
            p = doc.new_page(width=595, height=842)
            p.insert_text((50, 40), f"Candidate Name - Page {i+1}", fontsize=14)
            p.insert_text((50, 70), f"EXPERIENCE SECTION {i+1}", fontsize=12)
            for j in range(8):
                p.insert_text((50, 100 + j * 40), f"Senior Developer Role {i+1}.{j+1} | Tech Enterprise | 201{i} - 202{j%5}", fontsize=9)
                p.insert_text((50, 115 + j * 40), f"• Implemented key component {i+1}.{j+1} in high throughput pipeline.", fontsize=8)

        long_bytes = doc.tobytes()
        doc.close()

        extracted = UniversalDocumentExtractor.extract_document(long_bytes, "long_cv.pdf")
        self.assertEqual(extracted.page_count, 5)
        self.assertTrue(extracted.quality_score >= 0.75)
        self.assertTrue(len(extracted.raw_items) >= 40)

    # ── Test 12: DOCX Universal Extraction ──
    def test_11_docx_universal_extraction(self):
        import docx
        doc = docx.Document()
        doc.add_heading("Emily Watson", level=1)
        doc.add_paragraph("emily@example.com | +1 555 222 3333 | New York, NY")
        doc.add_heading("Summary", level=2)
        doc.add_paragraph("Product Manager with 6 years experience in SaaS platforms.")
        doc.add_heading("Experience", level=2)
        doc.add_paragraph("Senior Product Manager | Datadog | 2021 - Present")
        doc.add_paragraph("• Led product roadmap for APM observability suite.")

        buf = io.BytesIO()
        doc.save(buf)
        docx_bytes = buf.getvalue()

        extracted = UniversalDocumentExtractor.extract_document(docx_bytes, "emily_resume.docx")
        self.assertEqual(extracted.document_type, "docx")
        self.assertIn("Emily Watson", extracted.raw_text)
        self.assertIn("Datadog", extracted.raw_text)
        self.assertIn("Senior Product Manager", extracted.raw_text)


if __name__ == "__main__":
    unittest.main()
