"""init

Revision ID: 27aed39db389
Revises: 
Create Date: 2026-04-22 12:21:00.172584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '27aed39db389'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_interactions_id'), table_name='ai_interactions')
    op.drop_table('ai_interactions')
    op.drop_index(op.f('ix_companies_slug'), table_name='companies')
    op.drop_table('companies')
    op.drop_index(op.f('ix_meetings_session_id'), table_name='meetings')
    op.drop_table('meetings')
    op.drop_index(op.f('ix_leads_company_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_next_call_at'), table_name='leads')
    op.drop_index(op.f('ix_leads_phone_company'), table_name='leads')
    op.drop_index(op.f('ix_leads_status'), table_name='leads')
    op.drop_table('leads')
    op.drop_index(op.f('ix_company_scripts_company_id'), table_name='company_scripts')
    op.drop_index(op.f('ix_company_scripts_status'), table_name='company_scripts')
    op.drop_table('company_scripts')
    op.drop_index(op.f('ix_interview_slots_company_id'), table_name='interview_slots')
    op.drop_index(op.f('ix_interview_slots_lead_id'), table_name='interview_slots')
    op.drop_table('interview_slots')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interview_slots',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('lead_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('call_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('company_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('scheduled_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('confirmed', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('calendar_event_id', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('sms_sent', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_interview_slots_company'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], name=op.f('fk_interview_slots_lead'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('interview_slots_pkey'))
    )
    op.create_index(op.f('ix_interview_slots_lead_id'), 'interview_slots', ['lead_id'], unique=False)
    op.create_index(op.f('ix_interview_slots_company_id'), 'interview_slots', ['company_id'], unique=False)
    op.create_table('company_scripts',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('company_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('version', sa.VARCHAR(length=50), server_default=sa.text("'1.0'::character varying"), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'draft'::character varying"), autoincrement=False, nullable=False),
    sa.Column('steps', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('objection_responses', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('closing_hot', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('closing_warm', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('closing_cold', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('system_prompt_extra', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('uploaded_filename', sa.VARCHAR(length=300), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name='fk_company_scripts_company', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='company_scripts_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_company_scripts_status'), 'company_scripts', ['status'], unique=False)
    op.create_index(op.f('ix_company_scripts_company_id'), 'company_scripts', ['company_id'], unique=False)
    op.create_table('leads',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('company_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=False),
    sa.Column('qualification', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('experience_years', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('language_preference', sa.VARCHAR(length=10), server_default=sa.text("'ta'::character varying"), autoincrement=False, nullable=False),
    sa.Column('call_attempts', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('max_attempts', sa.INTEGER(), server_default=sa.text('3'), autoincrement=False, nullable=False),
    sa.Column('last_called_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('next_call_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('scheduled_interview_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('source_file', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('score', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_leads_company'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('leads_pkey'))
    )
    op.create_index(op.f('ix_leads_status'), 'leads', ['status'], unique=False)
    op.create_index(op.f('ix_leads_phone_company'), 'leads', ['phone', 'company_id'], unique=True)
    op.create_index(op.f('ix_leads_next_call_at'), 'leads', ['next_call_at'], unique=False)
    op.create_index(op.f('ix_leads_company_id'), 'leads', ['company_id'], unique=False)
    op.create_table('meetings',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('preferred_datetime', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('purpose', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('source', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('meetings_pkey'))
    )
    op.create_index(op.f('ix_meetings_session_id'), 'meetings', ['session_id'], unique=False)
    op.create_table('companies',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('slug', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('industry', sa.VARCHAR(length=100), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False),
    sa.Column('language', sa.VARCHAR(length=10), server_default=sa.text("'ta'::character varying"), autoincrement=False, nullable=False),
    sa.Column('agent_name', sa.VARCHAR(length=100), server_default=sa.text("'Agent'::character varying"), autoincrement=False, nullable=False),
    sa.Column('active_script_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['active_script_id'], ['company_scripts.id'], name=op.f('fk_companies_active_script')),
    sa.PrimaryKeyConstraint('id', name=op.f('companies_pkey'))
    )
    op.create_index(op.f('ix_companies_slug'), 'companies', ['slug'], unique=True)
    op.create_table('ai_interactions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('agent_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('mode', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('project_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('input_payload', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('ai_raw_response', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('ai_parsed_response', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('ai_interactions_pkey'))
    )
    op.create_index(op.f('ix_ai_interactions_id'), 'ai_interactions', ['id'], unique=False)
    # ### end Alembic commands ###
